steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-southeast2-docker.pkg.dev/gen-lang-client-0341860128/qos-platform/qos-ml-service:latest'
  - '-f'
  - 'docker/ml-service.Dockerfile'
  - 'ml-service'
images:
- 'asia-southeast2-docker.pkg.dev/gen-lang-client-0341860128/qos-platform/qos-ml-service:latest'
