#!/bin/bash
set -e

echo "=================================================="
echo "PATCH REAL TECHNICAL PDF/CSV EXPORT - NO SCREENSHOT"
echo "=================================================="

mkdir -p .backup-report-export

for f in \
  app/reports/page.tsx \
  app/globals.css \
  components/aksara-live-shell.tsx \
  package.json
do
  if [ -f "$f" ]; then
    cp "$f" ".backup-report-export/$(echo "$f" | tr '/' '_').bak"
    echo "Backup: $f"
  fi
done

echo "=================================================="
echo "1. INSTALL PDFKIT FOR SERVER-SIDE PDF"
echo "=================================================="

npm install pdfkit

echo "=================================================="
echo "2. ADD PRINT / EXPORT IGNORE CSS"
echo "=================================================="

cat >> app/globals.css <<'CSS'

/* Export safety: floating live widgets must never appear in print/PDF export */
@media print {
  .no-print,
  [data-export-ignore="true"],
  .aksara-floating-live-shell {
    display: none !important;
    visibility: hidden !important;
  }

  body {
    background: white !important;
  }
}
CSS

echo "=================================================="
echo "3. MARK FLOATING LIVE PANEL AS EXPORT-IGNORE"
echo "=================================================="

python3 <<'PY'
from pathlib import Path

p = Path("components/aksara-live-shell.tsx")

if not p.exists():
    print("⚠️ components/aksara-live-shell.tsx not found, skipped")
    raise SystemExit(0)

s = p.read_text()

s = s.replace(
    '<div className="fixed bottom-4 right-4 z-[2147483000] flex items-center gap-2">',
    '<div data-export-ignore="true" className="aksara-floating-live-shell no-print fixed bottom-4 right-4 z-[2147483000] flex items-center gap-2">'
)

s = s.replace(
    '<div className="fixed bottom-4 right-4 z-[2147483000] w-[430px] max-w-[calc(100vw-24px)] rounded-2xl border border-slate-700 bg-slate-950/95 p-4 text-white shadow-2xl backdrop-blur-xl">',
    '<div data-export-ignore="true" className="aksara-floating-live-shell no-print fixed bottom-4 right-4 z-[2147483000] w-[430px] max-w-[calc(100vw-24px)] rounded-2xl border border-slate-700 bg-slate-950/95 p-4 text-white shadow-2xl backdrop-blur-xl">'
)

p.write_text(s)
print("✅ Floating live panel marked as no-print/export-ignore")
PY

echo "=================================================="
echo "4. CREATE SERVER-SIDE CSV EXPORT ENDPOINT"
echo "=================================================="

mkdir -p app/api/reports/csv

cat > app/api/reports/csv/route.js <<'JS'
export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

const API_URL =
  process.env.NEXT_PUBLIC_API_URL ||
  process.env.API_URL ||
  "https://qos-api-gh3tn2a6oa-et.a.run.app";

function clean(value) {
  if (value === null || value === undefined) return "";
  return String(value).replaceAll('"', '""');
}

function csvRow(values) {
  return values.map((v) => `"${clean(v)}"`).join(",");
}

async function safeJson(url, fallback) {
  try {
    const res = await fetch(url, { cache: "no-store" });
    if (!res.ok) return fallback;
    return await res.json();
  } catch {
    return fallback;
  }
}

export async function GET() {
  const now = new Date();

  const [metrics, history, alerts] = await Promise.all([
    safeJson(`${API_URL}/api/qos/metrics?x=${Date.now()}`, {}),
    safeJson(`${API_URL}/api/qos/history?x=${Date.now()}`, []),
    safeJson(`${API_URL}/api/alerts?x=${Date.now()}`, []),
  ]);

  const rows = [];

  rows.push(csvRow([
    "section",
    "timestamp",
    "throughput_mbps",
    "latency_ms",
    "jitter_ms",
    "packet_loss_percent",
    "qoe_score",
    "streaming_status",
    "source",
    "alert_type",
    "alert_message",
    "alert_metric",
    "notes",
  ]));

  rows.push(csvRow([
    "report_metadata",
    now.toISOString(),
    "",
    "",
    "",
    "",
    "",
    "",
    "server-side-export",
    "",
    "",
    "",
    "Generated by AKSARA UNION technical export endpoint. This is not a screenshot.",
  ]));

  rows.push(csvRow([
    "live_summary",
    metrics.timestamp || "",
    metrics.throughput ?? "",
    metrics.latency ?? "",
    metrics.jitter ?? "",
    metrics.packet_loss ?? "",
    metrics.qoe_score ?? "",
    metrics.streaming_status ?? "",
    metrics.source ?? "",
    "",
    "",
    "",
    "Current live telemetry summary from real QoE probe.",
  ]));

  if (Array.isArray(history)) {
    history.forEach((item, index) => {
      rows.push(csvRow([
        `telemetry_sample_${index + 1}`,
        item.timestamp || "",
        item.throughput ?? "",
        item.latency ?? "",
        item.jitter ?? "",
        item.packet_loss ?? "",
        item.qoe_score ?? "",
        item.streaming_status || item.status || "",
        item.source || "",
        "",
        "",
        "",
        "Browser-to-Cloud Run QoE telemetry sample.",
      ]));
    });
  }

  if (Array.isArray(alerts) && alerts.length > 0) {
    alerts.forEach((alert, index) => {
      rows.push(csvRow([
        `active_alert_${index + 1}`,
        alert.time || "",
        "",
        "",
        "",
        "",
        "",
        "",
        alert.source || "",
        alert.type || "",
        alert.message || "",
        alert.metric || "",
        "Alert generated from real telemetry threshold evaluation.",
      ]));
    });
  } else {
    rows.push(csvRow([
      "active_alerts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "real-qoe-probe",
      "",
      "No active alerts",
      "",
      "Current telemetry is within acceptable threshold.",
    ]));
  }

  const csv = rows.join("\n");

  return new Response(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="AKSARA_QoS_Technical_Report_${now.toISOString().slice(0, 10)}.csv"`,
      "Cache-Control": "no-store, no-cache, must-revalidate",
    },
  });
}
JS

echo "=================================================="
echo "5. CREATE SERVER-SIDE TECHNICAL PDF EXPORT ENDPOINT"
echo "=================================================="

mkdir -p app/api/reports/pdf

cat > app/api/reports/pdf/route.js <<'JS'
export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

const PDFDocument = require("pdfkit");

const API_URL =
  process.env.NEXT_PUBLIC_API_URL ||
  process.env.API_URL ||
  "https://qos-api-gh3tn2a6oa-et.a.run.app";

async function safeJson(url, fallback) {
  try {
    const res = await fetch(url, { cache: "no-store" });
    if (!res.ok) return fallback;
    return await res.json();
  } catch {
    return fallback;
  }
}

function number(value, fallback = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function avg(items, key) {
  if (!Array.isArray(items) || items.length === 0) return 0;
  const values = items.map((x) => number(x?.[key])).filter((x) => Number.isFinite(x));
  if (!values.length) return 0;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

function max(items, key) {
  if (!Array.isArray(items) || items.length === 0) return 0;
  const values = items.map((x) => number(x?.[key])).filter((x) => Number.isFinite(x));
  if (!values.length) return 0;
  return Math.max(...values);
}

function min(items, key) {
  if (!Array.isArray(items) || items.length === 0) return 0;
  const values = items.map((x) => number(x?.[key])).filter((x) => Number.isFinite(x));
  if (!values.length) return 0;
  return Math.min(...values);
}

function fmt(value, digits = 2) {
  return number(value).toFixed(digits);
}

function statusFromQoe(qoe) {
  const x = number(qoe);
  if (x >= 90) return "EXCELLENT";
  if (x >= 75) return "STABLE";
  if (x >= 60) return "BUFFER RISK";
  return "POOR";
}

function severityText(alerts, metrics) {
  if (Array.isArray(alerts) && alerts.length > 0) return "ATTENTION REQUIRED";
  const qoe = number(metrics?.qoe_score);
  if (qoe >= 90) return "SLA PASSED";
  if (qoe >= 75) return "SLA WATCH";
  return "SLA RISK";
}

function drawTitle(doc, title, subtitle) {
  doc
    .fontSize(20)
    .fillColor("#0f172a")
    .text(title, { align: "left" });

  doc.moveDown(0.25);

  doc
    .fontSize(9)
    .fillColor("#475569")
    .text(subtitle, { align: "left" });

  doc.moveDown(1);
}

function drawSection(doc, title) {
  doc.moveDown(0.9);
  doc
    .fontSize(12)
    .fillColor("#0f172a")
    .text(title, { underline: false });

  doc
    .moveTo(doc.x, doc.y + 3)
    .lineTo(560, doc.y + 3)
    .strokeColor("#cbd5e1")
    .lineWidth(0.5)
    .stroke();

  doc.moveDown(0.7);
}

function drawKeyValueGrid(doc, rows) {
  const startX = doc.x;
  let y = doc.y;
  const colW = 255;
  const rowH = 34;

  rows.forEach((row, index) => {
    const col = index % 2;
    if (index > 0 && col === 0) y += rowH + 6;

    const x = startX + col * (colW + 12);

    doc
      .roundedRect(x, y, colW, rowH, 6)
      .fillAndStroke("#f8fafc", "#dbeafe");

    doc
      .fontSize(7)
      .fillColor("#64748b")
      .text(row.label, x + 10, y + 7, { width: colW - 20 });

    doc
      .fontSize(11)
      .fillColor("#0f172a")
      .text(row.value, x + 10, y + 18, { width: colW - 20 });
  });

  doc.y = y + rowH + 8;
}

function drawTable(doc, headers, rows, options = {}) {
  const startX = doc.x;
  let y = doc.y;
  const widths = options.widths || headers.map(() => Math.floor(520 / headers.length));
  const rowH = options.rowHeight || 22;

  function drawHeader() {
    let x = startX;
    doc.fontSize(7).fillColor("#ffffff");

    headers.forEach((h, i) => {
      doc.rect(x, y, widths[i], rowH).fillAndStroke("#0f172a", "#0f172a");
      doc.fillColor("#ffffff").text(h, x + 4, y + 7, { width: widths[i] - 8 });
      x += widths[i];
    });

    y += rowH;
  }

  drawHeader();

  rows.forEach((row, rowIndex) => {
    if (y > 745) {
      doc.addPage();
      y = 50;
      drawHeader();
    }

    let x = startX;
    const bg = rowIndex % 2 === 0 ? "#ffffff" : "#f8fafc";

    row.forEach((cell, i) => {
      doc.rect(x, y, widths[i], rowH).fillAndStroke(bg, "#e2e8f0");
      doc
        .fontSize(7)
        .fillColor("#0f172a")
        .text(String(cell ?? ""), x + 4, y + 7, { width: widths[i] - 8 });
      x += widths[i];
    });

    y += rowH;
  });

  doc.y = y + 8;
}

function addFooter(doc) {
  const range = doc.bufferedPageRange();

  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);

    doc
      .fontSize(7)
      .fillColor("#64748b")
      .text(
        `AKSARA UNION QoS Analytics Platform - Technical Report | Page ${i + 1} of ${range.count}`,
        36,
        810,
        { align: "center", width: 523 }
      );
  }
}

export async function GET() {
  const generatedAt = new Date();

  const [metrics, history, alerts, qoeLatest] = await Promise.all([
    safeJson(`${API_URL}/api/qos/metrics?x=${Date.now()}`, {}),
    safeJson(`${API_URL}/api/qos/history?x=${Date.now()}`, []),
    safeJson(`${API_URL}/api/alerts?x=${Date.now()}`, []),
    safeJson(`${API_URL}/api/qoe/latest?x=${Date.now()}`, {}),
  ]);

  const samples = Array.isArray(history) ? history.slice(0, 20) : [];
  const alertRows = Array.isArray(alerts) ? alerts : [];

  const summary = {
    sampleCount: samples.length,
    avgThroughput: avg(samples, "throughput"),
    avgLatency: avg(samples, "latency"),
    avgJitter: avg(samples, "jitter"),
    avgPacketLoss: avg(samples, "packet_loss"),
    avgQoe: avg(samples, "qoe_score"),
    maxLatency: max(samples, "latency"),
    minThroughput: min(samples, "throughput"),
    currentStatus: metrics?.streaming_status || statusFromQoe(metrics?.qoe_score),
    severity: severityText(alertRows, metrics),
  };

  const doc = new PDFDocument({
    size: "A4",
    margin: 36,
    bufferPages: true,
    info: {
      Title: "AKSARA UNION QoS Technical Report",
      Author: "AKSARA UNION QoS Analytics Platform",
      Subject: "Real Browser-to-Cloud QoE Telemetry Report",
    },
  });

  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  const done = new Promise((resolve) => doc.on("end", resolve));

  doc
    .rect(0, 0, 595, 80)
    .fill("#020617");

  doc
    .fontSize(9)
    .fillColor("#67e8f9")
    .text("AKSARA UNION", 36, 24);

  doc
    .fontSize(22)
    .fillColor("#ffffff")
    .text("QoS / QoE Technical SLA Report", 36, 38);

  doc
    .fontSize(8)
    .fillColor("#cbd5e1")
    .text("Server-side structured report. This PDF is generated from real telemetry data, not from a screenshot.", 36, 64);

  doc.y = 105;

  drawTitle(
    doc,
    "Executive Summary",
    "This report summarizes real browser-to-Cloud Run QoE measurements, including throughput, latency, jitter, packet loss, QoE score, and active threshold alerts."
  );

  drawKeyValueGrid(doc, [
    { label: "Generated At", value: generatedAt.toLocaleString("en-US") },
    { label: "Data Source", value: metrics?.source || "real-qoe-probe" },
    { label: "Current QoE Score", value: `${fmt(metrics?.qoe_score, 1)} / 100` },
    { label: "Current Status", value: summary.currentStatus },
    { label: "SLA Classification", value: summary.severity },
    { label: "Active Alerts", value: `${alertRows.length}` },
    { label: "Telemetry Samples", value: `${summary.sampleCount}` },
    { label: "Latest Timestamp", value: metrics?.timestamp || "-" },
  ]);

  drawSection(doc, "Live Telemetry Snapshot");

  drawKeyValueGrid(doc, [
    { label: "Current Throughput", value: `${fmt(metrics?.throughput, 2)} Mbps` },
    { label: "Current Latency", value: `${fmt(metrics?.latency, 2)} ms` },
    { label: "Current Jitter", value: `${fmt(metrics?.jitter, 2)} ms` },
    { label: "Packet Loss", value: `${fmt(metrics?.packet_loss, 2)} %` },
    { label: "Bandwidth Field", value: `${fmt(metrics?.bandwidth ?? metrics?.throughput, 2)} Mbps` },
    { label: "Streaming Status", value: metrics?.streaming_status || "-" },
  ]);

  drawSection(doc, "Measurement Window Statistics");

  drawKeyValueGrid(doc, [
    { label: "Average Throughput", value: `${fmt(summary.avgThroughput, 2)} Mbps` },
    { label: "Minimum Throughput", value: `${fmt(summary.minThroughput, 2)} Mbps` },
    { label: "Average Latency", value: `${fmt(summary.avgLatency, 2)} ms` },
    { label: "Maximum Latency", value: `${fmt(summary.maxLatency, 2)} ms` },
    { label: "Average Jitter", value: `${fmt(summary.avgJitter, 2)} ms` },
    { label: "Average Packet Loss", value: `${fmt(summary.avgPacketLoss, 2)} %` },
    { label: "Average QoE Score", value: `${fmt(summary.avgQoe, 2)} / 100` },
    { label: "Raw QoE Buffer Count", value: `${qoeLatest?.count ?? "-"}` },
  ]);

  drawSection(doc, "Active Alerts and Fault Conditions");

  if (alertRows.length > 0) {
    drawTable(
      doc,
      ["Type", "Message", "Metric", "Time", "Source"],
      alertRows.slice(0, 10).map((a) => [
        a.type || "-",
        a.message || "-",
        a.metric || "-",
        a.time || "-",
        a.source || "-",
      ]),
      { widths: [55, 180, 80, 80, 125], rowHeight: 24 }
    );
  } else {
    doc
      .fontSize(9)
      .fillColor("#166534")
      .text("No active alerts. Current telemetry is within the configured operating threshold.");
  }

  drawSection(doc, "Latest Real Telemetry Samples");

  if (samples.length > 0) {
    drawTable(
      doc,
      ["Timestamp", "Throughput", "Latency", "Jitter", "Loss", "QoE", "Source"],
      samples.slice(0, 15).map((s) => [
        s.timestamp || "-",
        `${fmt(s.throughput, 2)} Mbps`,
        `${fmt(s.latency, 2)} ms`,
        `${fmt(s.jitter, 2)} ms`,
        `${fmt(s.packet_loss, 2)} %`,
        `${fmt(s.qoe_score, 1)}`,
        s.source || "-",
      ]),
      { widths: [75, 82, 72, 70, 58, 50, 113], rowHeight: 23 }
    );
  } else {
    doc
      .fontSize(9)
      .fillColor("#b45309")
      .text("No telemetry samples are currently available. Open Streaming QoE or keep the dashboard active to feed the real browser-to-cloud probe.");
  }

  drawSection(doc, "Engineering Interpretation");

  const interpretation = [
    `The telemetry source is ${metrics?.source || "real-qoe-probe"}, meaning the data is generated from active browser-side probing toward the Cloud Run backend.`,
    `Current throughput is ${fmt(metrics?.throughput, 2)} Mbps with latency ${fmt(metrics?.latency, 2)} ms and jitter ${fmt(metrics?.jitter, 2)} ms.`,
    `The current QoE score is ${fmt(metrics?.qoe_score, 1)} and the interpreted streaming condition is ${metrics?.streaming_status || summary.currentStatus}.`,
    alertRows.length > 0
      ? `There are ${alertRows.length} active alert(s), so the platform classifies the condition as requiring engineering attention.`
      : "No active alert is present, so the platform currently considers the streaming condition operational.",
  ];

  doc
    .fontSize(9)
    .fillColor("#0f172a")
    .list(interpretation, {
      bulletRadius: 2,
      textIndent: 12,
      bulletIndent: 4,
      lineGap: 4,
    });

  drawSection(doc, "Methodology and Export Integrity");

  doc
    .fontSize(9)
    .fillColor("#0f172a")
    .text(
      "This report is generated server-side using structured telemetry endpoints. It does not capture the browser screen, does not include floating UI widgets, and does not depend on the visual layout of the dashboard. The exported PDF and CSV should therefore remain stable even when the dashboard UI changes.",
      { lineGap: 4 }
    );

  addFooter(doc);
  doc.end();

  await done;

  const pdfBuffer = Buffer.concat(chunks);

  return new Response(pdfBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="AKSARA_QoS_Technical_Report_${generatedAt.toISOString().slice(0, 10)}.pdf"`,
      "Cache-Control": "no-store, no-cache, must-revalidate",
    },
  });
}
JS

echo "=================================================="
echo "6. REBUILD REPORTS PAGE TO USE REAL SERVER EXPORT"
echo "=================================================="

cat > app/reports/page.tsx <<'TSX'
"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  Database,
  Download,
  FileSpreadsheet,
  FileText,
  Gauge,
  Radio,
  RefreshCw,
  ShieldCheck,
  Zap,
} from "lucide-react";

type Metric = {
  throughput?: number;
  latency?: number;
  jitter?: number;
  packet_loss?: number;
  bandwidth?: number;
  qoe_score?: number;
  streaming_status?: string;
  source?: string;
  timestamp?: string;
};

type AlertItem = {
  id?: string | number;
  type?: string;
  message?: string;
  metric?: string;
  time?: string;
  source?: string;
};

type HistoryItem = {
  timestamp?: string;
  throughput?: number;
  latency?: number;
  jitter?: number;
  packet_loss?: number;
  qoe_score?: number;
  source?: string;
  streaming_status?: string;
  status?: string;
};

function n(value: unknown, fallback = 0) {
  const x = Number(value);
  return Number.isFinite(x) ? x : fallback;
}

function fmt(value: unknown, digits = 2) {
  return n(value).toFixed(digits);
}

function avg(items: HistoryItem[], key: keyof HistoryItem) {
  if (!items.length) return 0;
  const values = items.map((item) => n(item[key])).filter((x) => Number.isFinite(x));
  if (!values.length) return 0;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

function max(items: HistoryItem[], key: keyof HistoryItem) {
  if (!items.length) return 0;
  const values = items.map((item) => n(item[key])).filter((x) => Number.isFinite(x));
  if (!values.length) return 0;
  return Math.max(...values);
}

function min(items: HistoryItem[], key: keyof HistoryItem) {
  if (!items.length) return 0;
  const values = items.map((item) => n(item[key])).filter((x) => Number.isFinite(x));
  if (!values.length) return 0;
  return Math.min(...values);
}

function download(url: string) {
  window.open(`${url}?x=${Date.now()}`, "_blank", "noopener,noreferrer");
}

function Card({
  label,
  value,
  unit,
  icon: Icon,
  accent,
  note,
}: {
  label: string;
  value: string | number;
  unit?: string;
  icon?: any;
  accent?: string;
  note?: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-xs uppercase tracking-[0.18em] text-slate-500">{label}</p>
          <div className="mt-3 flex items-end gap-2">
            <span className={`text-3xl font-black ${accent || "text-white"}`}>{value}</span>
            {unit ? <span className="mb-1 text-sm text-slate-400">{unit}</span> : null}
          </div>
          {note ? <p className="mt-2 text-xs text-slate-500">{note}</p> : null}
        </div>

        {Icon ? (
          <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-2">
            <Icon className="h-5 w-5 text-cyan-300" />
          </div>
        ) : null}
      </div>
    </div>
  );
}

export default function ReportsPage() {
  const [metrics, setMetrics] = useState<Metric>({});
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(false);

  const refresh = async () => {
    setLoading(true);

    try {
      const [metricRes, historyRes, alertRes] = await Promise.all([
        fetch(`/api/qos-metrics?x=${Date.now()}`, { cache: "no-store" }),
        fetch(`/api/qos-history?x=${Date.now()}`, { cache: "no-store" }),
        fetch(`/api/qos-alerts?x=${Date.now()}`, { cache: "no-store" }),
      ]);

      const metricJson = await metricRes.json();
      const historyJson = await historyRes.json();
      const alertJson = await alertRes.json();

      setMetrics(metricJson || {});
      setHistory(Array.isArray(historyJson) ? historyJson : []);
      setAlerts(Array.isArray(alertJson) ? alertJson : []);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    refresh();

    const interval = setInterval(refresh, 5000);

    const onRealtime = () => refresh();
    window.addEventListener("real-qoe-updated", onRealtime);

    return () => {
      clearInterval(interval);
      window.removeEventListener("real-qoe-updated", onRealtime);
    };
  }, []);

  const summary = useMemo(() => {
    return {
      avgThroughput: avg(history, "throughput"),
      minThroughput: min(history, "throughput"),
      avgLatency: avg(history, "latency"),
      maxLatency: max(history, "latency"),
      avgJitter: avg(history, "jitter"),
      avgPacketLoss: avg(history, "packet_loss"),
      avgQoe: avg(history, "qoe_score"),
      samples: history.length,
    };
  }, [history]);

  const slaPassed = alerts.length === 0 && n(metrics.qoe_score) >= 75;

  return (
    <main className="space-y-8 p-6 text-white">
      <section className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black">SLA / KPI Technical Report Generator</h1>
          <p className="mt-2 max-w-4xl text-slate-400">
            Structured server-side PDF and CSV export generated from real browser-to-Cloud Run QoE telemetry.
            This export does not capture the dashboard screen, so floating widgets will not appear in the report.
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <button
            onClick={refresh}
            className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-bold text-slate-300 hover:bg-slate-800"
          >
            <RefreshCw className="mr-2 inline h-4 w-4" />
            {loading ? "Refreshing..." : "Refresh Data"}
          </button>

          <button
            onClick={() => download("/api/reports/pdf")}
            className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-5 py-3 text-sm font-bold text-cyan-300 hover:bg-cyan-500/20"
          >
            <FileText className="mr-2 inline h-4 w-4" />
            Generate Technical PDF
          </button>

          <button
            onClick={() => download("/api/reports/csv")}
            className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-5 py-3 text-sm font-bold text-emerald-300 hover:bg-emerald-500/20"
          >
            <FileSpreadsheet className="mr-2 inline h-4 w-4" />
            Export Real CSV
          </button>
        </div>
      </section>

      <section
        className={`rounded-3xl border p-6 ${
          slaPassed
            ? "border-emerald-500/30 bg-emerald-500/10"
            : "border-red-500/30 bg-red-500/10"
        }`}
      >
        <div className="flex items-center gap-4">
          {slaPassed ? (
            <CheckCircle2 className="h-8 w-8 text-emerald-300" />
          ) : (
            <AlertTriangle className="h-8 w-8 text-red-300" />
          )}

          <div>
            <h2 className={`text-3xl font-black ${slaPassed ? "text-emerald-300" : "text-red-300"}`}>
              {slaPassed ? "SLA PASSED" : "SLA WATCH / RISK"}
            </h2>
            <p className="mt-1 text-sm text-slate-300">
              Current condition is calculated from real QoE score, active alerts, latency, jitter, and throughput.
            </p>
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-4">
        <Card
          label="Current Throughput"
          value={fmt(metrics.throughput)}
          unit="Mbps"
          icon={Zap}
          accent="text-cyan-300"
          note={metrics.source || "real-qoe-probe"}
        />
        <Card
          label="Current Latency"
          value={fmt(metrics.latency)}
          unit="ms"
          icon={Gauge}
          accent="text-yellow-300"
          note={metrics.timestamp || "-"}
        />
        <Card
          label="Current Jitter"
          value={fmt(metrics.jitter)}
          unit="ms"
          icon={Radio}
          accent="text-purple-300"
          note="Latency variation"
        />
        <Card
          label="QoE Score"
          value={fmt(metrics.qoe_score, 1)}
          unit="/100"
          icon={ShieldCheck}
          accent="text-emerald-300"
          note={metrics.streaming_status || "WAITING"}
        />
      </section>

      <section className="grid gap-4 md:grid-cols-4">
        <Card label="Average Throughput" value={fmt(summary.avgThroughput)} unit="Mbps" icon={Database} />
        <Card label="Min Throughput" value={fmt(summary.minThroughput)} unit="Mbps" icon={Download} />
        <Card label="Average Latency" value={fmt(summary.avgLatency)} unit="ms" icon={Gauge} />
        <Card label="Max Latency" value={fmt(summary.maxLatency)} unit="ms" icon={AlertTriangle} accent="text-yellow-300" />
        <Card label="Average Jitter" value={fmt(summary.avgJitter)} unit="ms" icon={Radio} />
        <Card label="Packet Loss" value={fmt(summary.avgPacketLoss)} unit="%" icon={AlertTriangle} accent="text-red-300" />
        <Card label="Average QoE" value={fmt(summary.avgQoe, 1)} unit="/100" icon={ShieldCheck} accent="text-emerald-300" />
        <Card label="Samples" value={summary.samples} icon={Database} note="real telemetry rows" />
      </section>

      <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-xl font-black">Export Integrity</h2>
            <p className="mt-2 text-sm text-slate-400">
              The PDF and CSV buttons above call server-side export endpoints. They do not use screen capture,
              browser print, html2canvas, or DOM screenshot. Therefore floating telemetry widgets and dashboard layout
              will not be embedded into the exported files.
            </p>
          </div>
        </div>

        <div className="mt-5 grid gap-4 md:grid-cols-3">
          <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-4">
            <p className="font-bold text-cyan-300">PDF Mode</p>
            <p className="mt-2 text-sm text-slate-300">
              Technical report generated from structured API data using server-side PDF rendering.
            </p>
          </div>

          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4">
            <p className="font-bold text-emerald-300">CSV Mode</p>
            <p className="mt-2 text-sm text-slate-300">
              Raw telemetry table containing timestamp, throughput, latency, jitter, packet loss, QoE, source, and alerts.
            </p>
          </div>

          <div className="rounded-xl border border-purple-500/20 bg-purple-500/10 p-4">
            <p className="font-bold text-purple-300">Data Source</p>
            <p className="mt-2 text-sm text-slate-300">
              Current source: <span className="font-bold">{metrics.source || "real-qoe-probe"}</span>.
            </p>
          </div>
        </div>
      </section>

      <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6">
        <h2 className="text-xl font-black">Active Alerts</h2>

        {alerts.length === 0 ? (
          <div className="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-300">
            No active alerts. Current telemetry is within operating threshold.
          </div>
        ) : (
          <div className="mt-5 overflow-hidden rounded-xl border border-slate-800">
            <table className="w-full text-left text-sm">
              <thead className="bg-slate-950 text-xs uppercase tracking-[0.18em] text-slate-500">
                <tr>
                  <th className="p-3">Type</th>
                  <th className="p-3">Message</th>
                  <th className="p-3">Metric</th>
                  <th className="p-3">Time</th>
                  <th className="p-3">Source</th>
                </tr>
              </thead>
              <tbody>
                {alerts.map((alert, index) => (
                  <tr key={alert.id || index} className="border-t border-slate-800">
                    <td className="p-3 text-red-300">{alert.type || "-"}</td>
                    <td className="p-3">{alert.message || "-"}</td>
                    <td className="p-3">{alert.metric || "-"}</td>
                    <td className="p-3">{alert.time || "-"}</td>
                    <td className="p-3 text-cyan-300">{alert.source || "-"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6">
        <h2 className="text-xl font-black">Latest Telemetry Sample Window</h2>

        <div className="mt-5 overflow-hidden rounded-xl border border-slate-800">
          <table className="w-full text-left text-sm">
            <thead className="bg-slate-950 text-xs uppercase tracking-[0.18em] text-slate-500">
              <tr>
                <th className="p-3">Timestamp</th>
                <th className="p-3">Throughput</th>
                <th className="p-3">Latency</th>
                <th className="p-3">Jitter</th>
                <th className="p-3">Loss</th>
                <th className="p-3">QoE</th>
                <th className="p-3">Source</th>
              </tr>
            </thead>

            <tbody>
              {history.slice(0, 15).map((item, index) => (
                <tr key={index} className="border-t border-slate-800">
                  <td className="p-3">{item.timestamp || "-"}</td>
                  <td className="p-3 text-cyan-300">{fmt(item.throughput)} Mbps</td>
                  <td className="p-3 text-yellow-300">{fmt(item.latency)} ms</td>
                  <td className="p-3 text-purple-300">{fmt(item.jitter)} ms</td>
                  <td className="p-3 text-red-300">{fmt(item.packet_loss)}%</td>
                  <td className="p-3 text-emerald-300">{fmt(item.qoe_score, 1)}</td>
                  <td className="p-3">{item.source || "-"}</td>
                </tr>
              ))}

              {history.length === 0 ? (
                <tr>
                  <td colSpan={7} className="p-6 text-center text-slate-500">
                    No telemetry samples available yet. Open Streaming QoE or keep the dashboard active to feed the real probe.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
TSX

echo "=================================================="
echo "PATCH DONE"
echo "=================================================="
